config/routes.rb
Rails.application.routes.draw do

  resources :requests

end

app/models/request.rb
class Request < ActiveRecord::Base
  validates :name, presence: true, length: {minimum: 3, maximum: 30}
  validates :email, presence: true, length: {maximum: 250}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def new
    @request = Request.new
  end

  def edit
    @request = Request.find(params[:id])
  end

  def index
    @requests = Request.all
  end

  def create
    @request = Request.new(request_params)
    if @request.save
      flash[:notice] = "Request Successfully Submitted"
      redirect_to request_path(@request)
    else
      render "new"
    end
  end

    def update
      @request = Request.find(params[:id])
      if @request.update(request_params)
        flash[:notice] = "Submission was Successfully Edited"
        redirect_to request_path(@request)
      else
        render "edit"
      end
    end

    def show
      @request = Request.find(params[:id])
    end

    def destroy
      @request = Request.find(params[:id])
      @request.destroy
      flash[:notice] = "Submission was Successfully Deleted"
      redirect_to requests_path
    end

  end

  private

  def request_params
    params.require(:request).permit(:name, :email, :department, :message,)

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Supporter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
  <% end %>
<%= yield %>

</body>
</html>

app/views/requests/_form.html.erb
<% if @request.errors.any? %>
<h3>The following errors prevented your request from being submitted:</h3>
<ul>
  <% @request.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @request do |f| %>

<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
</div>
<div>
  <br>
</div>
<div>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
</div>
  <br>
<div>
</div>
<div>
  <label for="department">Department</label><br>
  <input id="department_id_1" name="department" value "1" type="radio">
  <label for="department_id_1">Sales</label>
  <input id="department_id_2" name="department" value "2" type="radio">
  <label for="department_id_2">Marketing</label>
  <input id="department_id_3" name="department" value "3" type="radio">
  <label for="department_id_3">Technical</label>
</div>
<br>
<div>
  <%= f.label :message %><br>
  <%= f.text_area :message %>
</div>
<div>
  <br>
</div>
<div>
  <%= f.submit "SAVE" %>
</div>


  <% end %>

  <%= link_to "Back to submissions", requests_path %>

app/views/requests/edit.html.erb
<h1>Edit Submission</h1>

<%= render "form" %>

app/views/requests/index.html.erb
<h1>List of All Support Requests</h1>
<div>
  <%= link_to "Submit New Request", new_request_path %>
</div><br>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
  </tr>

  <% @requests.each do |request| %>
  <tr>
    <td><%= request.name %></td>
    <td><%= request.email %></td>
    <td><%= request.department %></td>
    <td><%= request.message %></td>
    <td><%= link_to "Edit", edit_request_path(request) %></td>
    <td><%= link_to "Show", request_path(request) %></td>
    <td><%= link_to "Delete", request_path(request), method: :delete, data: {confirm: "Are you sure?"} %></td>

  </tr>
  <% end %>

</table>

app/views/requests/new.html.erb
<h1>Sumitt a Request for Support</h1>

<%= render "form" %>

app/views/requests/show.html.erb
<h1>Showing selected request</h1>

<p>
  Name: <%= @request.name %>
</p>

<p>
  Email: <%= @request.email %>
</p>

<p>
  Department: <%= @request.department %>
</p>

<p>
  Message: <%= @request.message %>
</p>

<%= link_to "Edit this submission", edit_request_path(@request) %>
|
<%= link_to "Back to submissions", requests_path %>